Update drawpile-installer-official-build-from-sources-with-listserver-and-webadmin2

diff --git a/testing/drawpile-installer-official-build-from-sources-with-listserver-and-webadmin2 b/testing/drawpile-installer-official-build-from-sources-with-listserver-and-webadmin2
--- a/testing/drawpile-installer-official-build-from-sources-with-listserver-and-webadmin2
+++ b/testing/drawpile-installer-official-build-from-sources-with-listserver-and-webadmin2
@@ -1,5 +1,5 @@
 #!/bin/bash
-drawpilescriptversion=2.996003911
+drawpilescriptversion=2.996003912
 drawpile_script_version=$drawpilescriptversion
 if echo $SSH_TTY | grep -q "/dev/pts/" ; then
 	local_or_remote="Remote"
@@ -2894,7 +2894,7 @@ if [ "`systemctl is-enabled mini-httpd.service`" = "enabled" ]; then
 	echo "${bold}${red}Mini-HTTPD is enabled, disabling and stopping service.${normal}"
 	sudo systemctl disable mini-httpd.service
 	sudo systemctl stop --now mini-httpd.service
-	if [[ "`systemctl is-enabled nginx.service`" = "enabled" && "`systemctl is-active nginx.service`" = "failed" ]]; then
+	if [[ "`systemctl is-enabled nginx.service`" = "enabled" && ( "`systemctl is-active nginx.service`" = "failed" || "`systemctl is-active nginx.service`" = "inactive" )) ]]; then
 		echo "${bold}${red}NGINX is failed and enabled, restarting service.${normal}"
 		echo "${bold}${red}Likely due to mini-httpd being enabled.${normal}"
 		sudo systemctl stop --now nginx.service
@@ -2909,7 +2909,7 @@ if [ "`systemctl is-enabled mini-httpd.service`" = "enabled" ]; then
 elif [[ "`systemctl is-active mini-httpd.service`" = "active" ]]; then
 	echo "${bold}${red}Mini-HTTPD is not enabled but running, stopping service.${normal}"
 	sudo systemctl stop --now mini-httpd.service
-	if [[ "`systemctl is-enabled nginx.service`" = "enabled" && "`systemctl is-active nginx.service`" = "failed" ]]; then
+	if [[ "`systemctl is-enabled nginx.service`" = "enabled" && ( "`systemctl is-active nginx.service`" = "failed" || "`systemctl is-active nginx.service`" = "inactive" )) ]]; then
 		echo "${bold}${red}NGINX is failed and enabled, restarting service.${normal}"
 		echo "${bold}${red}Likely due to mini-httpd being enabled.${normal}"
 		sudo systemctl stop --now nginx.service
@@ -2922,7 +2922,8 @@ elif [[ "`systemctl is-active mini-httpd.service`" = "active" ]]; then
 		echo "${bold}${yellow}NGINX is not currently running.${normal}"
 	fi
 else
-	echo "${bold}${green}Mini-HTTPD is not enabled.${normal}"
+	echo "${bold}${green}Mini-HTTPD is not enabled nor running.${normal}"
+	echo "${bold}${green}No action required.${normal}"
 fi
 echo
 echo '--------------------------------------------------------------------------------'
@@ -13772,7 +13773,138 @@ EOF
 		done
 		echo
 		if [ "$fail2ban_status" == "yes" ] || [ "$fail2ban_status" == "YES" ] || [ "$fail2ban_status" == "Yes" ] || [ "$fail2ban_status" == "Y" ] || [ "$fail2ban_status" == "y" ]; then
-			sudo $package_install_program fail2ban # || echo "" && echo "${bold}${red}Installation failed.${normal}" && echo "" && sleep 30
+			python_version=$( python --version | awk '{ print $2 }' | perl -0777 -ne '/([0-9]+\.[0-9]+)/; print $1' )
+
+			function fail2ban_typical_system_installation () {
+				sudo $package_install_program fail2ban # || echo "" && echo "${bold}${red}Installation failed.${normal}" && echo "" && sleep 30
+				echo
+				if [ "`systemctl is-enabled fail2ban.service`" = "disabled" ]; then
+					echo "Enabling Fail2ban service."
+					sudo systemctl enable fail2ban.service
+				fi
+				echo
+				systemctl status fail2ban.service --no-pager -l
+				echo
+				if [ "`systemctl is-active fail2ban.service`" = "inactive" ]; then
+					echo "Starting Fail2ban service."
+					sudo systemctl start --now fail2ban.service
+					systemctl status fail2ban.service --no-pager -l
+				fi
+			}
+
+			if [ "$python_version" == "3.12" ]; then
+				echo "${bold}${red}Executing manual install process, Python 3.12 causes issues in Ubuntu 24.04 currently.${normal}"
+				sudo $package_install_program python3-pyinotify python3-systemd
+
+				sudo mkdir -p -v "/tmp/f2b"
+				cd /tmp/f2b
+				if [ -e "/etc/fail2ban/jail.local" ]; then
+					if [ -e "/tmp/f2b/jail.local" ]; then
+						rm -f "/tmp/f2b/jail.local"
+					fi
+					cp "/etc/fail2ban/jail.local" "/tmp/f2b"
+				fi
+
+				# if [[ "$what_linux_name" != "NAME=\"Fedora Linux\"" && "$what_linux_name" != "NAME=Fedora" ]]; then
+				if [ "$what_linux_flavor" == "PRETTY_NAME=\"Ubuntu 24.04 LTS\"" ]; then
+					echo "${bold}${yellow}Executing manual install - debian based.${normal}"
+					# Manually install - Debian based
+					#     https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually
+
+					# cd /tmp/
+					# 1) download deb package and signature:
+					wget -O fail2ban.deb https://github.com/fail2ban/fail2ban/releases/download/1.1.0/fail2ban_1.1.0-1.upstream1_all.deb
+					wget -O fail2ban.deb.asc https://github.com/fail2ban/fail2ban/releases/download/1.1.0/fail2ban_1.1.0-1.upstream1_all.deb.asc
+
+					# 2) check signature (if you want to be sure file is unmodified):
+					# gpg --verify fail2ban.deb.asc fail2ban.deb
+
+					# 3) view details of the package:
+					# dpkg -I fail2ban.deb
+
+					# 4) to ensure the upgrade run gentler (protocol of previous version may be incompatible), stop fail2ban before install:
+					# using service:
+					sudo service fail2ban stop
+					# using client:
+					sudo fail2ban-client stop
+
+					# 5a) either install package using dpkg (standalone package, don't regard dependencies):
+					sudo dpkg -i fail2ban.deb
+					# if the package introduces some "broken" dependencies (I don't think so in case of fail2ban which has few dependencies),
+					# to fix the unmet dependency issue, run this:
+					sudo apt -f install
+
+					# 5b) alternatively install package using gdebi (that will take care of installation of dependencies):
+					# sudo gdebi fail2ban.deb
+					# if you want to check anyway whether there are some broken packages and fix them automatically, you can run:
+					# sudo apt -f install
+					
+					if [ -e "/tmp/f2b/jail.local" ]; then
+						mv -f "/tmp/f2b/jail.local" "/etc/fail2ban"
+					fi
+					sudo service enable fail2ban.service
+					sudo service start --now fail2ban.service
+				else
+					echo "Python3.12 is installed. Some systems may have problems with"
+					echo "installing Fail2Ban properly. It's recommended to try a regular"
+					echo "installation before attempting manual, read the log output "
+					echo "carefully. If it fails or doesn't appear to work correctly "
+					echo "(can test by entering the incorrect username and/or password "
+					echo "to log into one of the web admin interfaces 15 times in less "
+					echo "than 10 minutes. The 16th attempt should not load the web "
+					echo "page for 10 minutes before you can try again."
+					echo ""
+					echo "Would you like to try a manual install?"
+					echo ""
+					echo "1 - yes - manual install"
+					echo "2 - no  - try regular installation."
+					echo ""
+					while :; do
+						read -r -p "${bold}${cyan}Without quotes, type '1' or '2':${normal} " fail2ban_manual_install_query
+						echo
+						if [ "$fail2ban_manual_install_query" == "1" ] || [ "$fail2ban_manual_install_query" == "2" ]; then
+							break
+						else
+							echo
+							echo "${bold}${red}Invalid input selection, try again.${normal}"
+							echo
+							echo ----------------------------------------------------------------------------------
+							echo
+						fi
+					done
+					if [ "$fail2ban_manual_install_query" == "1" ]; then
+						echo "${bold}${yellow}Executing manual install with tar file.${normal}"
+						# Manually install - Debian based
+						#     https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually
+						# Release 1.1.0 - 2024-04-05
+						#     https://github.com/fail2ban/fail2ban/releases/tag/1.1.0
+						sudo $wget_or_wget2_quiet_progress -O 1.1.0.tar.gz https://github.com/fail2ban/fail2ban/archive/refs/tags/1.1.0.tar.gz
+						sudo tar vzxf 1.1.0.tar.gz
+						cd fail2ban-1.1.0
+						sudo service fail2ban stop --now
+						
+						sudo python setup.py install --without-tests
+						sudo cp ./build/fail2ban.service /etc/systemd/system/fail2ban.service
+						sudo systemctl enable fail2ban
+						if [ -e "/tmp/f2b/jail.local" ]; then
+							mv -f "/tmp/f2b/jail.local" "/etc/fail2ban"
+						fi
+						sudo fail2ban-client --test
+						sudo service fail2ban start --now
+					elif [ "$fail2ban_manual_install_query" == "2" ]; then
+						fail2ban_typical_system_installation
+					else
+						echo "This message should not be visible for fail2ban manual installation."
+						fail2ban_typical_system_installation
+					fi
+				fi
+			else
+				fail2ban_typical_system_installation
+			fi
+			echo
+			systemctl status fail2ban.service --no-pager -l
+			echo
+			echo
 			if [ "$local_or_remote" == "Remote" ]; then
 				echo
 				echo "${bold}${cyan}***** Configure Fail2Ban for SSH or not . . . *****${normal}"
